import { useState, useRef, useEffect, useMemo } from 'react';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

interface ScanChatProps {
  onClose?: () => void;
  leadName?: string;
}

const inlineParse = (str: string): string => {
  return str.replace(
    /\*\*(.+?)\*\*/g,
    '<strong class="text-caramelo font-semibold">$1</strong>'
  );
};

const parseMarkdown = (text: string): string => {
  const lines = text.split('\n');
  const result: string[] = [];
  let inTable = false;
  let tableRows: string[][] = [];
  let listType: 'ul' | 'ol' | null = null;

  const flushTable = () => {
    if (tableRows.length === 0) return;
    let html = '<table class="scan-table">';
    tableRows.forEach((cells, idx) => {
      if (idx === 1 && cells.every((c) => /^[-:]+$/.test(c.trim()))) return;
      const tag = idx === 0 ? 'th' : 'td';
      html += '<tr>';
      cells.forEach((cell) => {
        html += `<${tag}>${inlineParse(cell.trim())}</${tag}>`;
      });
      html += '</tr>';
    });
    html += '</table>';
    result.push(html);
    tableRows = [];
  };

  const flushList = () => {
    if (listType === 'ul') result.push('</ul>');
    if (listType === 'ol') result.push('</ol>');
    listType = null;
  };

  for (const line of lines) {
    const trimmed = line.trim();

    // Table row
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      if (!inTable) {
        if (listType) flushList();
        inTable = true;
        tableRows = [];
      }
      const cells = trimmed
        .slice(1, -1)
        .split('|')
        .map((c) => c.trim());
      tableRows.push(cells);
      continue;
    } else if (inTable) {
      inTable = false;
      flushTable();
    }

    // Unordered list item
    if (/^[-*]\s+/.test(trimmed)) {
      if (listType !== 'ul') {
        if (listType) flushList();
        listType = 'ul';
        result.push('<ul class="scan-list">');
      }
      const content = trimmed.replace(/^[-*]\s+/, '');
      result.push(`<li>${inlineParse(content)}</li>`);
      continue;
    }

    // Ordered list item
    if (/^\d+\.\s+/.test(trimmed)) {
      if (listType !== 'ol') {
        if (listType) flushList();
        listType = 'ol';
        result.push('<ol class="scan-list-ordered">');
      }
      const content = trimmed.replace(/^\d+\.\s+/, '');
      result.push(`<li>${inlineParse(content)}</li>`);
      continue;
    }

    // Non-list line breaks the list
    if (listType) flushList();

    // Empty line
    if (trimmed === '') {
      result.push('<div class="h-3" aria-hidden="true"></div>');
      continue;
    }

    // Regular paragraph
    result.push(`<p>${inlineParse(trimmed)}</p>`);
  }

  // Flush remaining structures
  if (inTable) {
    inTable = false;
    flushTable();
  }
  if (listType) flushList();

  return result.join('\n');
};

const RenderedMarkdown = ({ content }: { content: string }) => {
  const html = useMemo(() => parseMarkdown(content), [content]);
  // Content is generated by our own parseMarkdown — not user-supplied HTML
  return <div className="scan-prose" dangerouslySetInnerHTML={{ __html: html }} />;
};

export const ScanChat = ({ onClose, leadName: initialLeadName }: ScanChatProps) => {
  const [leadName, setLeadName] = useState(initialLeadName || '');
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [started, setStarted] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    if (started && !isStreaming) {
      inputRef.current?.focus();
    }
  }, [started, isStreaming]);

  // Listen for scan-start event from Astro page
  useEffect(() => {
    const handler = ((e: CustomEvent) => {
      if (!started) {
        const name = e.detail?.leadName || '';
        if (name) setLeadName(name);
        handleStart(name);
      }
    }) as EventListener;
    window.addEventListener('scan-start', handler);
    return () => window.removeEventListener('scan-start', handler);
  }, [started]);

  const sendMessage = async (userMessage: string, allMessages: Message[] = messages) => {
    const newMessages: Message[] = [...allMessages, { role: 'user', content: userMessage }];
    setMessages(newMessages);
    setInput('');
    setIsStreaming(true);

    try {
      const response = await fetch('/api/scan/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: newMessages }),
      });

      if (!response.ok) {
        throw new Error('Erro na conexão');
      }

      const reader = response.body?.getReader();
      if (!reader) throw new Error('Stream indisponível');

      const decoder = new TextDecoder();
      let assistantMessage = '';

      setMessages([...newMessages, { role: 'assistant', content: '' }]);

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n').filter((line) => line.startsWith('data: '));

        for (const line of lines) {
          const data = line.slice(6);
          if (data === '[DONE]') continue;

          try {
            const parsed = JSON.parse(data);
            if (parsed.text) {
              assistantMessage += parsed.text;
              setMessages([
                ...newMessages,
                { role: 'assistant', content: assistantMessage },
              ]);
            }
            if (parsed.error) {
              assistantMessage += `\n\n[Erro: ${parsed.error}]`;
              setMessages([
                ...newMessages,
                { role: 'assistant', content: assistantMessage },
              ]);
            }
          } catch {
            // skip malformed chunks
          }
        }
      }
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : 'Erro desconhecido';
      setMessages([
        ...newMessages,
        { role: 'assistant', content: `Desculpe, ocorreu um erro: ${errorMsg}. Tente novamente.` },
      ]);
    } finally {
      setIsStreaming(false);
    }
  };

  const handleStart = (name?: string) => {
    setStarted(true);
    const initialMessage: Message[] = [];
    const resolvedName = name || leadName;
    const greeting = resolvedName
      ? `Olá, sou ${resolvedName} e quero fazer meu Scan de Autoridade Cadarn.`
      : 'Olá, quero fazer meu Scan de Autoridade Cadarn.';
    sendMessage(greeting, initialMessage);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isStreaming) return;
    sendMessage(input.trim());
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      if (!input.trim() || isStreaming) return;
      sendMessage(input.trim());
    }
  };

  if (!started) {
    return null;
  }

  const lastMessage = messages[messages.length - 1];
  const isAssistantStreaming = isStreaming && lastMessage?.role === 'assistant';
  const showLoadingPlaceholder = isStreaming && lastMessage?.role !== 'assistant';

  return (
    <div
      className="fixed inset-0 z-[100] flex flex-col bg-navy"
      aria-label="Conversa com Analista de Autoridade Cadarn"
      role="region"
    >
      {/* Header */}
      <header className="flex items-center justify-between border-b border-offwhite/10 px-4 py-3 sm:px-6">
        <div className="flex items-center gap-3">
          <div className="h-px w-6 bg-caramelo" aria-hidden="true" />
          <span className="font-mono text-xs uppercase tracking-widest text-offwhite/50">
            Scan de Autoridade Cadarn
          </span>
        </div>
        {onClose && (
          <button
            onClick={onClose}
            className="font-mono text-xs uppercase tracking-widest text-offwhite/40 transition-colors hover:text-offwhite"
            aria-label="Fechar conversa"
          >
            Fechar
          </button>
        )}
      </header>

      {/* Messages */}
      <div
        className="flex-1 overflow-y-auto px-4 py-8 sm:px-6"
        role="log"
        aria-live="polite"
        aria-busy={isStreaming}
        aria-label="Mensagens da conversa"
      >
        <div className="mx-auto max-w-2xl space-y-8">
          {messages.map((msg, i) => (
            <article
              key={i}
              className={
                msg.role === 'assistant'
                  ? 'border-l-2 border-caramelo/60 pl-5 sm:pl-6'
                  : 'flex justify-end'
              }
              aria-label={msg.role === 'assistant' ? 'Mensagem do analista' : 'Sua mensagem'}
            >
              {msg.role === 'assistant' ? (
                <div
                  className={
                    isAssistantStreaming && i === messages.length - 1
                      ? 'typing-cursor'
                      : ''
                  }
                >
                  <RenderedMarkdown content={msg.content} />
                </div>
              ) : (
                <div className="max-w-[80%] bg-offwhite/[0.06] px-4 py-2.5">
                  <p className="font-body text-sm leading-relaxed text-offwhite/70">
                    {msg.content}
                  </p>
                </div>
              )}
            </article>
          ))}

          {showLoadingPlaceholder && (
            <div
              className="border-l-2 border-caramelo/60 pl-5 sm:pl-6"
              role="status"
              aria-label="Analista processando resposta"
            >
              <div className="h-4 w-48 animate-pulse bg-offwhite/[0.06]" />
              <div className="mt-2.5 h-4 w-32 animate-pulse bg-offwhite/[0.04]" />
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input */}
      <div className="border-t border-offwhite/10 px-4 py-4 sm:px-6">
        <form
          onSubmit={handleSubmit}
          className="mx-auto flex max-w-2xl items-end gap-3"
          aria-label="Formulário de resposta"
        >
          <div className="flex-1">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={isStreaming}
              rows={1}
              aria-label="Sua mensagem"
              placeholder={isStreaming ? 'Aguarde...' : 'Sua resposta...'}
              className="w-full resize-none border-0 border-b border-offwhite/20 bg-transparent px-0 py-2 font-body text-sm text-offwhite placeholder:text-offwhite/30 focus:border-caramelo focus:outline-none focus:ring-0 disabled:opacity-40"
            />
          </div>
          <button
            type="submit"
            disabled={isStreaming || !input.trim()}
            aria-label="Enviar mensagem"
            className="mb-1 text-caramelo transition-opacity hover:opacity-80 disabled:opacity-20"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="h-5 w-5"
              aria-hidden="true"
            >
              <path d="M3.105 2.288a.75.75 0 0 0-.826.95l1.414 4.926A1.5 1.5 0 0 0 5.135 9.25h6.115a.75.75 0 0 1 0 1.5H5.135a1.5 1.5 0 0 0-1.442 1.086l-1.414 4.926a.75.75 0 0 0 .826.95l15.5-6.5a.75.75 0 0 0 0-1.424l-15.5-6.5Z" />
            </svg>
          </button>
        </form>
      </div>
    </div>
  );
};

export default ScanChat;
